### ISSUE TITLE
[Bug] Failed to start the node: Loaded a ledger with inconsistent state 

### ISSUE THREAD

**Issue by oursy** [AleoHQ/snarkOS#1345]
## 🐛 Bug Report

After the automatic update, the error 
'Failed to start the node: Loaded a ledger with inconsistent state (16383 != 16384) (unable to automatically resolve)', src/main.rs:48:28  

Try to delete the file `posw.proving.b0086c7` but it has no effect.

(Write your description here)

## Steps to Reproduce

1.  Run`./run-miner.sh`
2.  See error

![image](https://user-images.githubusercontent.com/9456577/143785201-0ea00957-140a-4720-9f06-734771b7428b.png)

## Your Environment
snarkOS Version : Compiling snarkos 2.0.0
Computer OS : Ubuntu 20.04

**Comment by MemberIT** [comment]
Your Environment
snarkOS Version : Compiling snarkos 2.0.0
Computer OS : Ubuntu 20.04

Got a similar error when automatically updating from git testnet2 branch:
```
Nov 29 12:15:25 node1 snarkos[92057]:          ╦╬╬╬╬╬╦
Nov 29 12:15:25 node1 snarkos[92057]:         ╬╬╬╬╬╬╬╬╬                    ▄▄▄▄        ▄▄▄
Nov 29 12:15:25 node1 snarkos[92057]:        ╬╬╬╬╬╬╬╬╬╬╬                  ▐▓▓▓▓▌       ▓▓▓
Nov 29 12:15:25 node1 snarkos[92057]:       ╬╬╬╬╬╬╬╬╬╬╬╬╬                ▐▓▓▓▓▓▓▌      ▓▓▓     ▄▄▄▄▄▄       ▄▄▄▄▄▄
Nov 29 12:15:25 node1 snarkos[92057]:      ╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬              ▐▓▓▓  ▓▓▓▌     ▓▓▓   ▄▓▓▀▀▀▀▓▓▄   ▐▓▓▓▓▓▓▓▓▌
Nov 29 12:15:25 node1 snarkos[92057]:     ╬╬╬╬╬╬╬╜ ╙╬╬╬╬╬╬╬            ▐▓▓▓▌  ▐▓▓▓▌    ▓▓▓  ▐▓▓▓▄▄▄▄▓▓▓▌ ▐▓▓▓    ▓▓▓▌
Nov 29 12:15:25 node1 snarkos[92057]:    ╬╬╬╬╬╬╣     ╠╬╬╬╬╬╬           █▓▓▓▓▓▓▓▓▓▓█    ▓▓▓  ▐▓▓▀▀▀▀▀▀▀▀▘ ▐▓▓▓    ▓▓▓▌
Nov 29 12:15:25 node1 snarkos[92057]:   ╬╬╬╬╬╬╣       ╠╬╬╬╬╬╬         █▓▓▓▌    ▐▓▓▓█   ▓▓▓   ▀▓▓▄▄▄▄▓▓▀   ▐▓▓▓▓▓▓▓▓▌
Nov 29 12:15:25 node1 snarkos[92057]:  ╬╬╬╬╬╬╣         ╠╬╬╬╬╬╬       ▝▀▀▀▀      ▀▀▀▀▘  ▀▀▀     ▀▀▀▀▀▀       ▀▀▀▀▀▀
Nov 29 12:15:25 node1 snarkos[92057]: ╚╬╬╬╬╬╩           ╩╬╬╬╬╩
Nov 29 12:15:25 node1 snarkos[92057]: Welcome to Aleo! We thank you for running a network node and supporting privacy.
Nov 29 12:15:25 node1 snarkos[92057]: Your Aleo address is aleoXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Nov 29 12:15:25 node1 snarkos[92057]: Starting a mining node on testnet2.
Nov 29 12:15:25 node1 snarkos[92057]: thread 'main' panicked at 'Failed to start the node: Loaded a ledger with inconsistent state (20854 != 20855) (unable to automatically resolve)', src/main.rs:48:28
Nov 29 12:15:25 node1 snarkos[92057]: stack backtrace:
Nov 29 12:15:25 node1 snarkos[92057]:    0:     0x55ff9ea0dedc - std::backtrace_rs::backtrace::libunwind::trace::h3fea1eb2e0ba2ac9
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
Nov 29 12:15:25 node1 snarkos[92057]:    1:     0x55ff9ea0dedc - std::backtrace_rs::backtrace::trace_unsynchronized::h849d83492cbc0d59
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
Nov 29 12:15:25 node1 snarkos[92057]:    2:     0x55ff9ea0dedc - std::sys_common::backtrace::_print_fmt::he3179d37290f23d3
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
Nov 29 12:15:25 node1 snarkos[92057]:    3:     0x55ff9ea0dedc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h140f6925cad14324
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
Nov 29 12:15:25 node1 snarkos[92057]:    4:     0x55ff9e57ce6c - core::fmt::write::h31b9cd1bedd7ea38
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
Nov 29 12:15:25 node1 snarkos[92057]:    5:     0x55ff9ea07375 - std::io::Write::write_fmt::h1fdf66f83f70913e
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
Nov 29 12:15:25 node1 snarkos[92057]:    6:     0x55ff9ea0f870 - std::sys_common::backtrace::_print::he7ac492cd19c3189
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
Nov 29 12:15:25 node1 snarkos[92057]:    7:     0x55ff9ea0f870 - std::sys_common::backtrace::print::hba20f8920229d8e8
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
Nov 29 12:15:25 node1 snarkos[92057]:    8:     0x55ff9ea0f870 - std::panicking::default_hook::{{closure}}::h714d63979ae18678
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
Nov 29 12:15:25 node1 snarkos[92057]:    9:     0x55ff9ea100ba - std::panicking::default_hook::hf1afb64e69563ca8
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
Nov 29 12:15:25 node1 snarkos[92057]:   10:     0x55ff9ea100ba - std::panicking::rust_panic_with_hook::h02231a501e274a13
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:624:17
Nov 29 12:15:25 node1 snarkos[92057]:   11:     0x55ff9ea0f9ba - std::panicking::begin_panic_handler::{{closure}}::h5b5e738edf361af7
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521:13
Nov 29 12:15:25 node1 snarkos[92057]:   12:     0x55ff9ea0e5f4 - std::sys_common::backtrace::__rust_end_short_backtrace::h601a115def7987b1
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
Nov 29 12:15:25 node1 snarkos[92057]:   13:     0x55ff9ea0f93d - rust_begin_unwind
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
Nov 29 12:15:25 node1 snarkos[92057]:   14:     0x55ff9de03301 - core::panicking::panic_fmt::h7a58c8fffc5559a4
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
Nov 29 12:15:25 node1 snarkos[92057]:   15:     0x55ff9de033f3 - core::result::unwrap_failed::h1036b5c6eb8030dd
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
Nov 29 12:15:25 node1 snarkos[92057]:   16:     0x55ff9df85595 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h851369fc78a74e1a
Nov 29 12:15:25 node1 snarkos[92057]:   17:     0x55ff9e592f77 - tokio::park::thread::CachedParkThread::block_on::ha5eb1b172f4da854
Nov 29 12:15:25 node1 snarkos[92057]:   18:     0x55ff9e37e56c - tokio::runtime::thread_pool::ThreadPool::block_on::h24cfc5d78a7cdcc8
Nov 29 12:15:25 node1 snarkos[92057]:   19:     0x55ff9e61982e - tokio::runtime::Runtime::block_on::hc9b160b7dba8b383
Nov 29 12:15:25 node1 snarkos[92057]:   20:     0x55ff9e2be1c2 - snarkos::main::h22725f95a7a9bce1
Nov 29 12:15:25 node1 snarkos[92057]:   21:     0x55ff9ea82ec3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf7da4909013d8eec
Nov 29 12:15:25 node1 snarkos[92057]:   22:     0x55ff9e05419d - std::rt::lang_start::{{closure}}::hd7f3007862f2d333
Nov 29 12:15:25 node1 snarkos[92057]:   23:     0x55ff9ea1081f - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2790017aba790142
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:259:13
Nov 29 12:15:25 node1 snarkos[92057]:   24:     0x55ff9ea1081f - std::panicking::try::do_call::hd5d0fbb7d2d2d85d
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
Nov 29 12:15:25 node1 snarkos[92057]:   25:     0x55ff9ea1081f - std::panicking::try::h675520ee37b0fdf7
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
Nov 29 12:15:25 node1 snarkos[92057]:   26:     0x55ff9ea1081f - std::panic::catch_unwind::h803430ea0284ce79
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
Nov 29 12:15:25 node1 snarkos[92057]:   27:     0x55ff9ea1081f - std::rt::lang_start_internal::{{closure}}::h3a398a8154de3106
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:48
Nov 29 12:15:25 node1 snarkos[92057]:   28:     0x55ff9ea1081f - std::panicking::try::do_call::hf60f106700df94b2
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
Nov 29 12:15:25 node1 snarkos[92057]:   29:     0x55ff9ea1081f - std::panicking::try::hb2022d2bc87a9867
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
Nov 29 12:15:25 node1 snarkos[92057]:   30:     0x55ff9ea1081f - std::panic::catch_unwind::hbf801c9d61f0c2fb
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
Nov 29 12:15:25 node1 snarkos[92057]:   31:     0x55ff9ea1081f - std::rt::lang_start_internal::hdd488b91dc742b96
Nov 29 12:15:25 node1 snarkos[92057]:                                at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:20
Nov 29 12:15:25 node1 snarkos[92057]:   32:     0x55ff9e2be352 - main
Nov 29 12:15:25 node1 snarkos[92057]:   33:     0x7fd8d14c20b3 - __libc_start_main
Nov 29 12:15:25 node1 snarkos[92057]:   34:     0x55ff9de6c16e - _start
Nov 29 12:15:25 node1 snarkos[92057]:   35:                0x0 - <unknown>
```
ready to provide more detailed information if necessary. I kept a copy of the ledger.

**Comment by ljedrz** [comment]
This issue should have improved (or be resolved altogether) with https://github.com/AleoHQ/snarkOS/pull/1327, but I'll keep it open in case it can still occur. Please report if you encounter it with the current version of the node.

**Comment by howardwu** [comment]
Closing as this issue has been marked likely fixed.
