### ISSUE TITLE
[Bug]"thread 'main' panicked at 'assertion failed: `(left == right)`" error reported at miner process startup

### ISSUE THREAD

**Issue by daveyhook** [AleoHQ/snarkOS#1804]
error output when ./run-miner.sh was executed:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', /home/aleoer/snarkOS/storage/src/state/ledger.rs:829:9
stack backtrace:
   0:     0x559bbeaabf04 - std::backtrace_rs::backtrace::libunwind::trace::h22893a5306c091b4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x559bbeaabf04 - std::backtrace_rs::backtrace::trace_unsynchronized::h29c3bc6f9e91819d
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x559bbeaabf04 - std::sys_common::backtrace::_print_fmt::he497d8a0ec903793
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x559bbeaabf04 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c2a9d2774d81873
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x559bbe48b93c - core::fmt::write::hba4337c43d992f49
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
   5:     0x559bbeaa4d65 - std::io::Write::write_fmt::heb73de6e02cfabed
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
   6:     0x559bbeaad9be - std::sys_common::backtrace::_print::h63c8b24acdd8e8ce
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x559bbeaad9be - std::sys_common::backtrace::print::h426700d6240cdcc2
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x559bbeaad9be - std::panicking::default_hook::{{closure}}::hc9a76eed0b18f82b
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
   9:     0x559bbeaad6ed - std::panicking::default_hook::h2e88d02087fae196
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
  10:     0x559bbeaadf65 - std::panicking::rust_panic_with_hook::habfdcc2e90f9fd4c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:698:17
  11:     0x559bbeaade74 - std::panicking::begin_panic_handler::{{closure}}::he054b2a83a51d2cd
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:588:13
  12:     0x559bbeaac434 - std::sys_common::backtrace::__rust_end_short_backtrace::ha48b94ab49b30915
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x559bbeaadbdd - rust_begin_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
  14:     0x559bbd9ab1f3 - core::panicking::panic_fmt::h366d3a309ae17c94
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
  15:     0x559bbe489498 - core::panicking::assert_failed_inner::h92c01a43e8afd9c2
  16:     0x559bbd992d7b - core::panicking::assert_failed::h0afed2b842a8abf8
  17:     0x559bbe2e17f3 - snarkos_storage::state::ledger::LedgerState<N,A>::open_writer::h84365f772fc94a9d
  18:     0x559bbe13c441 - snarkos::server::Server<N,E>::initialize::{{closure}}::h1ced08fef4dc324e
  19:     0x559bbe135852 - snarkos::node::Node::start::{{closure}}::h7e1285296f7e6019
  20:     0x559bbe2738b4 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he0d87f1409318364
  21:     0x559bbe4a8745 - tokio::park::thread::CachedParkThread::block_on::h1ced8b5596b46190
  22:     0x559bbdcd3eac - tokio::runtime::thread_pool::ThreadPool::block_on::hfe01ccff791c5424
  23:     0x559bbdb0848c - tokio::runtime::Runtime::block_on::h42e5289d557699be
  24:     0x559bbdba59cf - snarkos::main::h7f1b7930bc4b4307
  25:     0x559bbdd79eb3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h026ed719a62c3e1c
  26:     0x559bbdbb52cd - std::rt::lang_start::{{closure}}::heaa9240b34352ae0
  27:     0x559bbea9f5cb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::had4f69b3aefb47a8
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
  28:     0x559bbea9f5cb - std::panicking::try::do_call::hf2ad5355fcafe775
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  29:     0x559bbea9f5cb - std::panicking::try::h0a63ac363423e61e
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  30:     0x559bbea9f5cb - std::panic::catch_unwind::h18088edcecb8693a
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  31:     0x559bbea9f5cb - std::rt::lang_start_internal::{{closure}}::ha7dad166dc711761
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
  32:     0x559bbea9f5cb - std::panicking::try::do_call::hda0c61bf3a57d6e6
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  33:     0x559bbea9f5cb - std::panicking::try::hbc940e68560040a9
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  34:     0x559bbea9f5cb - std::panic::catch_unwind::haed0df2aeb3fa368
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  35:     0x559bbea9f5cb - std::rt::lang_start_internal::h9c06694362b5b80c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
  36:     0x559bbdba5ae2 - main
  37:     0x7f74bfbd00b3 - __libc_start_main
  38:     0x559bbda2c39e - _start
  39:                0x0 - <unknown>

```

## Your Environment
```
snarkOS Version: v2.0.2
Rust Version: 1.61.0
Computer OS: Ubuntu Server 20.04.3 LTS
```

**Comment by ljedrz** [comment]
Just to confirm: this is the `testnet3` branch, correct? Also, is this a fresh ledger?

**Comment by daveyhook** [comment]
> Just to confirm: this is the `testnet3` branch, correct? Also, is this a fresh ledger?
What does "a fresh ledger" mean?I deleted the git folder and retry again:
```
git clone https://github.com/AleoHQ/snarkOS.git --depth 1
cd snarkOS
source $HOME/.cargo/env
cargo run --release -- --miner aleo1xxxxxxxx --trial --verbosity 2
```
The same log reappears:
```
   Compiling snarkos-storage v2.0.2 (/home/aleoer/snarkOS/storage)
   Compiling snarkos-network v2.0.2 (/home/aleoer/snarkOS/network)
   Compiling snarkos-rpc v2.0.2 (/home/aleoer/snarkOS/rpc)
   Compiling snarkos v2.0.2 (/home/aleoer/snarkOS)
    Finished release [optimized] target(s) in 2m 11s
     Running `target/release/snarkos --miner aleo1xxxxxxxx --trial --verbosity 2`


         ╦╬╬╬╬╬╦
        ╬╬╬╬╬╬╬╬╬                    ▄▄▄▄        ▄▄▄
       ╬╬╬╬╬╬╬╬╬╬╬                  ▐▓▓▓▓▌       ▓▓▓
      ╬╬╬╬╬╬╬╬╬╬╬╬╬                ▐▓▓▓▓▓▓▌      ▓▓▓     ▄▄▄▄▄▄       ▄▄▄▄▄▄
     ╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬              ▐▓▓▓  ▓▓▓▌     ▓▓▓   ▄▓▓▀▀▀▀▓▓▄   ▐▓▓▓▓▓▓▓▓▌
    ╬╬╬╬╬╬╬╜ ╙╬╬╬╬╬╬╬            ▐▓▓▓▌  ▐▓▓▓▌    ▓▓▓  ▐▓▓▓▄▄▄▄▓▓▓▌ ▐▓▓▓    ▓▓▓▌
   ╬╬╬╬╬╬╣     ╠╬╬╬╬╬╬           █▓▓▓▓▓▓▓▓▓▓█    ▓▓▓  ▐▓▓▀▀▀▀▀▀▀▀▘ ▐▓▓▓    ▓▓▓▌
  ╬╬╬╬╬╬╣       ╠╬╬╬╬╬╬         █▓▓▓▌    ▐▓▓▓█   ▓▓▓   ▀▓▓▄▄▄▄▓▓▀   ▐▓▓▓▓▓▓▓▓▌
 ╬╬╬╬╬╬╣         ╠╬╬╬╬╬╬       ▝▀▀▀▀      ▀▀▀▀▘  ▀▀▀     ▀▀▀▀▀▀       ▀▀▀▀▀▀
╚╬╬╬╬╬╩           ╩╬╬╬╬╩

Welcome to Aleo! We thank you for running a network node and supporting privacy.

Your Aleo address is aleo1xxxxxxxx.

Starting a mining node on testnet2.


 ==================================================================================================

                         Welcome to Aleo Testnet3 - Incentivization Period

 ==================================================================================================

     The incentivized testnet will be announced on Discord. Visit https://www.aleo.org/discord
     for the official launch announcement on Month Date, Year, from the Aleo team.

     Minimum requirements:

         - CPU: 16-cores (32-cores preferred)
         - RAM: 16GB of memory (32GB preferred)
         - Storage: 128GB of disk space
         - Network: 50 Mbps of upload and download bandwidth

     To get started (after Month Date, Year):

         1. Generate one Aleo account, and save the account private key and view key.
         2. Ensure ports 4132/tcp and 3032/tcp are open on your router and OS firewall.
         3. Ensure your Aleo node is running the `run-client.sh` or `run-miner.sh` script,
            in order to automatically stay up to date on the incentivized testnet.
         4. File technical issues on Github at https://github.com/AleoHQ/snarkOS/issues/new/choose
         5. Ask questions on Discord at https://www.aleo.org/discord
         6. Please be respectful to all members of the Aleo community.

     To claim rewards (after Month Date, Year):

         1. Participants will be required to KYC at the end of incentivized testnet3.
         2. Participants must demonstrate ownership of their Aleo miner address.
         3. [For United States & Canada] Participants must be accredited investors.
         4. The Aleo team reserves the right to maintain discretion in rewarding participants.

     Thank you for participating in incentivized testnet3 and for supporting privacy!

 ==================================================================================================

     Your Aleo miner address is aleo1xxxxxxxx

 ==================================================================================================

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', /home/aleoer/snarkOS/storage/src/state/ledger.rs:829:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Note:
 Running the same thing on another machine with an OS version of Ubuntu Server 20.04.2 LTS is perfectly fine :-)

**Comment by ljedrz** [comment]
> What does "a fresh ledger" mean?I deleted the git folder and retry again

A fresh ledger would be one without any blocks.

The ledger is not stored in the folder of the repository, but rather in your `home` folder, i.e. `~/.aleo/storage`.

It's still weird that it would happen, especially with the very first block; can you clear the storage and retry? That should fix it.

**Comment by daveyhook** [comment]
> > What does "a fresh ledger" mean?I deleted the git folder and retry again
> 
> A fresh ledger would be one without any blocks.
> 
> The ledger is not stored in the folder of the repository, but rather in your `home` folder, i.e. `~/.aleo/storage`.
> 
> It's still weird that it would happen, especially with the very first block; can you clear the storage and retry? That should fix it.

It works!Thank you very much.
