### ISSUE TITLE
[Bug] Invalid block version found

### ISSUE THREAD

**Issue by ljedrz** [AleoHQ/snarkOS#1873]
```
2022-08-19T08:04:08.087640Z TRACE Requesting block 2262 of 6631
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid block version', /home/ljedrz/git/snarkOS/snarkos/ledger/mod.rs:257:81
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(8395), ...)', /home/ljedrz/git/snarkOS/snarkos/ledger/mod.rs:277:22
```
note: the line numbers might be a bit off, as I'm tinkering with the branch; in any case, the issue is with block parsing:
```
let block = Block::from_bytes_le(&block_bytes.unwrap()).unwrap();
```

**Comment by ljedrz** [comment]
Somewhat surprisingly, a restart seems to have resumed syncing just fine.

**Comment by mlsmith** [comment]
I'm having the same issue. Rerunning it fixes it for a while.  First time I ran it I only got 0% of the way through. After rerunning, I only made it 6% of the way through.  The last time I ran it I made it to 13%.  I'll keep trying, though.

```
2022-08-22T22:39:05.203496Z  INFO Synced up to block 100 of 13342 - 0% complete (est. 9 minutes remaining)
2022-08-22T22:39:05.203507Z TRACE Requesting block 200 of 13342
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid block version', /home/michaels/snarkOS/snarkos/ledger/mod.rs:255:81
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(574), ...)', /home/michaels/snarkOS/snarkos/ledger/mod.rs:276:22
```

```
2022-08-22T22:42:42.865967Z  INFO Synced up to block 836 of 13349 - 6% complete (est. 9 minutes remaining)
2022-08-22T22:42:42.865978Z TRACE Requesting block 936 of 13349
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid block version', /home/michaels/snarkOS/snarkos/ledger/mod.rs:255:81
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(3202), ...)', /home/michaels/snarkOS/snarkos/ledger/mod.rs:276:22
```

```
2022-08-22T22:45:03.211196Z  INFO Synced up to block 1852 of 13353 - 13% complete (est. 9 minutes remaining)
2022-08-22T22:45:03.211207Z TRACE Requesting block 1952 of 13353
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid block version', /home/michaels/snarkOS/snarkos/ledger/mod.rs:255:81
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(4305), ...)', /home/michaels/snarkOS/snarkos/ledger/mod.rs:276:22
```

**Comment by mlsmith** [comment]
FYI, I needed to restart about 4 more times (7 runs in total) and now I've caught up.

**Comment by yuliyu123** [comment]
I have similar issue reported:
```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("vm.aleo.org")), port: None, path: "/testnet3/block/testnet3/5011.block", query: None, fragment: None }, source: hyper::Error(Connect, Error { code: -9806, message: "connection closed via error" }) }', /Users/looperX/Devlop/aleo/snarkOS/snarkos/ledger/mod.rs:255:48
```

**Comment by teenu4** [comment]
I'm facing the same issue and after restart sync continues.

**Comment by mumup** [comment]
emmmmm...total 23767, (56/56)

**Comment by yuliyu123** [comment]
Can we sync success now?

**Comment by UnNicky** [comment]
In all the logs (from different nodes' owners) it shows exactly 100 gap between last synced and requesting blocks, may be it's a clue? I'm configuring new node and it's sync barely reached 500 blocks after I don't know how many restarts.

**Comment by underway2014** [comment]
same error,  When will this bug be fixed

**Comment by ljedrz** [comment]
I haven't been able to trigger this issue with the branch in this PR: https://github.com/AleoHQ/snarkOS/pull/1896.

**Comment by pablodeymo** [comment]
I think this issue should be reopened as it is still happens.
See also: #1891 and #1943

**Comment by ljedrz** [comment]
The root cause is different now (the server can't handle the volume of requests), but yes, the reported error is the same.

**Comment by pablodeymo** [comment]
I think I’m having the same error as stated in this [issue](https://github.com/AleoHQ/snarkOS/issues/1943) about Block parse error (the other issue probably is caused by the request volume as you said).

**Comment by pablodeymo** [comment]
I haven't seen the comment you put in that issue.

**Comment by ljedrz** [comment]
No worries, I added it only after your comment here 👌

**Comment by erickingxu** [comment]
any solutions for this ?
