### ISSUE TITLE
[Feature] error: thread 'main' panicked at 'The license in "./display/src/pages/overview.rs"

### ISSUE THREAD

**Issue by liolikus** [AleoHQ/snarkOS#2405]
## 🚀 Feature
```
error: failed to run custom build command for `snarkos v2.0.2 (/root/leo/snarkOS)`

Caused by:
  process didn't exit successfully: `/root/leo/snarkOS/target/release/build/snarkos-e900855db5584cfc/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'The license in "./display/src/pages/overview.rs" is either missing or it doesn't match the expected string!', build.rs:46:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `snarkos v2.0.2 (/root/leo/snarkOS)`, intermediate artifacts can be found at `/root/leo/snarkOS/target`
```

## Motivation

It appears that something went wrong in the latest build, and many users are experiencing issues as a result.

## Full log
```
RUN_BACKTRACE=1 cargo install --path .       Fetch [====================>    ]  85.87%, (16762/20758) resolving deltas                                          Downloaded digest v0.10.7
  Downloaded console v0.15.7
  Downloaded proc-macro2 v1.0.58
  Downloaded aleo-std v0.1.18
  Downloaded aleo-std-profiler v0.1.15
  Downloaded subtle v2.5.0
  Downloaded universal-hash v0.4.0
  Downloaded ctr v0.7.0
  Downloaded aleo-std-time v0.1.2
  Downloaded aleo-std-cpu v0.1.4
  Downloaded base64 v0.21.1
  Downloaded aes-gcm v0.9.2
  Downloaded reqwest v0.11.18
  Downloaded regex v1.8.2
  Downloaded regex-syntax v0.7.2
  Downloaded linux-raw-sys v0.3.8
  Downloaded curl-sys v0.4.62+curl-8.1.0
  Downloaded 17 crates (5.3 MB) in 8.77s (largest was `curl-sys` at 3.2 MB)
   Compiling libc v0.2.144
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.58
   Compiling quote v1.0.27
   Compiling unicode-ident v1.0.8
   Compiling autocfg v1.1.0
   Compiling serde v1.0.163
   Compiling scopeguard v1.1.0
   Compiling smallvec v1.10.0
   Compiling syn v2.0.16
   Compiling parking_lot_core v0.9.7
   Compiling version_check v0.9.4
   Compiling jobserver v0.1.26
   Compiling num_cpus v1.15.0
   Compiling cc v1.0.79
   Compiling itoa v1.0.6
   Compiling crossbeam-utils v0.8.15
   Compiling memoffset v0.8.0
   Compiling crossbeam-epoch v0.9.14
   Compiling rayon-core v1.11.0
   Compiling memchr v2.5.0
   Compiling crossbeam-channel v0.5.8
   Compiling crossbeam-deque v0.8.3
   Compiling once_cell v1.17.1
   Compiling either v1.8.1
   Compiling indexmap v1.9.3
   Compiling hashbrown v0.12.3
   Compiling rayon v1.7.0
   Compiling syn v1.0.109
   Compiling typenum v1.16.0
   Compiling generic-array v0.14.7
   Compiling serde_json v1.0.96
   Compiling ryu v1.0.13
   Compiling serde_derive v1.0.163
   Compiling getrandom v0.2.9
   Compiling rand_core v0.6.4
   Compiling num-traits v0.2.15
   Compiling lock_api v0.4.9
   Compiling num-integer v0.1.45
   Compiling num-bigint v0.4.3
   Compiling thiserror v1.0.40
   Compiling ppv-lite86 v0.2.17
   Compiling pkg-config v0.3.27
   Compiling rand_chacha v0.3.1
   Compiling parking_lot v0.12.1
   Compiling thiserror-impl v1.0.40
   Compiling dirs-sys v0.3.7
   Compiling dirs v4.0.0
   Compiling rand v0.8.5
   Compiling anyhow v1.0.71
   Compiling aleo-std-storage v0.1.3
   Compiling aleo-std-timed v0.1.2
   Compiling aleo-std-time v0.1.2
   Compiling socket2 v0.4.9
   Compiling aleo-std-profiler v0.1.15
   Compiling aleo-std-cpu v0.1.4
   Compiling aleo-std-timer v0.1.2
   Compiling aleo-std v0.1.18
   Compiling rand_xorshift v0.3.0
   Compiling bincode v1.3.3
   Compiling snarkvm-utilities-derives v0.11.2
   Compiling subtle v2.5.0
   Compiling derivative v2.2.0
   Compiling openssl-sys v0.9.87
   Compiling itertools v0.10.5
   Compiling cpufeatures v0.2.7
   Compiling minimal-lexical v0.2.1
   Compiling nom v7.1.3
   Compiling snarkvm-utilities v0.11.2
   Compiling log v0.4.17
   Compiling bech32 v0.9.1
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.4
   Compiling snarkvm-fields v0.11.2
   Compiling digest v0.10.7
   Compiling lazy_static v1.4.0
   Compiling libz-sys v1.1.9
   Compiling openssl-probe v0.1.5
   Compiling curl-sys v0.4.62+curl-8.1.0
   Compiling ahash v0.8.3
   Compiling snarkvm-curves v0.11.2
   Compiling atty v0.2.14
   Compiling arrayvec v0.7.2
   Compiling curl v0.4.44
   Compiling paste v1.0.12
   Compiling pin-project-lite v0.2.9
   Compiling sha2 v0.10.6
   Compiling constant_time_eq v0.2.5
   Compiling byteorder v1.4.3
   Compiling arrayref v0.3.7
   Compiling blake2s_simd v1.0.1
   Compiling fxhash v0.2.1
   Compiling snarkvm-console-network-environment v0.11.2
   Compiling snarkvm-console-types-boolean v0.11.2
   Compiling snarkvm-console-types-field v0.11.2
   Compiling snarkvm-console-types-scalar v0.11.2
   Compiling snarkvm-console-types-integers v0.11.2
   Compiling colored v2.0.0
   Compiling snarkvm-console-types-group v0.11.2
   Compiling snarkvm-console-types-address v0.11.2
   Compiling snarkvm-console-types-string v0.11.2
   Compiling blake2 v0.10.6
   Compiling hex v0.4.3
   Compiling snarkvm-console-types v0.11.2
   Compiling snarkvm-console-algorithms v0.11.2
   Compiling hashbrown v0.13.2
   Compiling snarkvm-r1cs v0.11.2
   Compiling snarkvm-console-collections v0.11.2
   Compiling bytes v1.4.0
   Compiling futures-core v0.3.28
   Compiling signal-hook-registry v1.4.1
   Compiling mio v0.8.6
   Compiling tracing-core v0.1.31
   Compiling snarkvm-circuit-types-boolean v0.11.2
   Compiling snarkvm-circuit-environment-witness v0.11.2
   Compiling futures-sink v0.3.28
   Compiling bitflags v1.3.2
   Compiling tracing-attributes v0.1.24
   Compiling tokio v1.28.1
   Compiling slab v0.4.8
   Compiling snarkvm-circuit-types-field v0.11.2
   Compiling futures-task v0.3.28
   Compiling futures-channel v0.3.28
   Compiling tokio-macros v2.1.0
   Compiling pin-utils v0.1.0
   Compiling futures-util v0.3.28
   Compiling futures-macro v0.3.28
   Compiling futures-io v0.3.28
   Compiling fnv v1.0.7
   Compiling snarkvm-circuit-types-scalar v0.11.2
   Compiling http v0.2.9
   Compiling tracing v0.1.37
   Compiling snarkvm-circuit-types-group v0.11.2
   Compiling snarkvm-circuit-types-integers v0.11.2
   Compiling ring v0.16.20
   Compiling glob v0.3.1
   Compiling snarkvm-circuit-types-address v0.11.2
   Compiling snarkvm-circuit-types-string v0.11.2
   Compiling clang-sys v1.6.1
   Compiling percent-encoding v2.2.0
   Compiling prettyplease v0.2.5
   Compiling form_urlencoded v1.1.0
   Compiling tokio-util v0.7.8
   Compiling untrusted v0.7.1
   Compiling snarkvm-circuit-algorithms v0.11.2
   Compiling unicode-xid v0.0.4
   Compiling spin v0.5.2
   Compiling tinyvec_macros v0.1.1
   Compiling tower-service v0.3.2
   Compiling semver v1.0.17
   Compiling libloading v0.7.4
   Compiling tinyvec v1.6.0
   Compiling synom v0.11.3
   Compiling http-body v0.4.5
   Compiling base64 v0.13.1
   Compiling httparse v1.8.0
   Compiling quote v0.3.15
   Compiling regex-syntax v0.7.2
   Compiling snarkvm-circuit-collections v0.11.2
   Compiling bs58 v0.4.0
   Compiling bindgen v0.65.1
   Compiling syn v0.11.11
   Compiling cexpr v0.6.0
   Compiling unicode-normalization v0.1.22
   Compiling regex v1.8.2
   Compiling lz4-sys v1.9.4
   Compiling snarkvm-circuit-network v0.11.2
   Compiling shlex v1.1.0
   Compiling peeking_take_while v0.1.2
   Compiling rustc-hash v1.1.0
   Compiling lazycell v1.3.0
   Compiling unicode-bidi v0.3.13
   Compiling foreign-types-shared v0.1.1
   Compiling openssl v0.10.52
   Compiling httpdate v1.0.2
   Compiling try-lock v0.2.4
   Compiling want v0.3.0
   Compiling idna v0.3.0
   Compiling foreign-types v0.3.2
   Compiling enum_index_derive v0.2.0
   Compiling h2 v0.3.19
   Compiling num-derive v0.3.3
   Compiling openssl-macros v0.1.1
   Compiling native-tls v0.2.11
   Compiling snarkvm-circuit-account v0.11.2
   Compiling enum_index v0.2.0
   Compiling crc32fast v1.3.2
   Compiling mime v0.3.17
   Compiling url v2.3.1
   Compiling librocksdb-sys v0.11.0+8.1.1
   Compiling hyper v0.14.26
   Compiling webpki v0.22.0
   Compiling proc-macro-error-attr v1.0.4
   Compiling portable-atomic v1.3.2
   Compiling adler v1.0.2
   Compiling rustls v0.20.8
   Compiling io-lifetimes v1.0.10
   Compiling snarkvm-circuit-program v0.11.2
   Compiling miniz_oxide v0.7.1
   Compiling sct v0.7.0
   Compiling serde_urlencoded v0.7.1
   Compiling proc-macro-error v1.0.4
   Compiling unicode-width v0.1.10
   Compiling portable-atomic v0.3.20
   Compiling rustix v0.37.19
   Compiling flate2 v1.0.26
   Compiling tokio-native-tls v0.3.1
   Compiling webpki-roots v0.22.6
   Compiling aho-corasick v1.0.1
   Compiling base64 v0.21.1
   Compiling rustversion v1.0.12
   Compiling opaque-debug v0.3.0
   Compiling linux-raw-sys v0.3.8
   Compiling async-trait v0.1.68
   Compiling ureq v2.6.2
   Compiling hyper-tls v0.5.0
   Compiling console v0.15.7
   Compiling universal-hash v0.4.0
   Compiling cipher v0.3.0
   Compiling encoding_rs v0.8.32
   Compiling number_prefix v0.4.0
   Compiling heck v0.4.1
   Compiling platforms v3.0.2
   Compiling fastrand v1.9.0
   Compiling time-core v0.1.1
   Compiling self_update v0.36.0
   Compiling ipnet v2.7.2
   Compiling os_str_bytes v6.5.0
   Compiling clap_lex v0.2.4
   Compiling reqwest v0.11.18
   Compiling time-macros v0.2.9
   Compiling tempfile v3.5.0
   Compiling clap_derive v3.2.25
   Compiling indicatif v0.17.3
   Compiling quick-xml v0.23.1
   Compiling strsim v0.10.0
   Compiling termcolor v1.2.0
   Compiling urlencoding v2.1.2
   Compiling textwrap v0.16.0
   Compiling time v0.3.21
   Compiling clap v3.2.25
   Compiling num-format v0.4.4
   Compiling zeroize v1.6.0
   Compiling curve25519-dalek v4.0.0-rc.1
   Compiling rustc_version v0.4.0
   Compiling polyval v0.5.3
   Compiling aead v0.4.3
   Compiling tower-layer v0.3.2
   Compiling virtue v0.0.13
   Compiling ghash v0.4.4
   Compiling snow v0.9.2
   Compiling chacha20 v0.8.2
   Compiling bincode_derive v2.0.0-rc.3
   Compiling axum-core v0.3.4
   Compiling aes v0.7.5
   Compiling ctr v0.7.0
   Compiling poly1305 v0.7.2
   Compiling pin-project-internal v1.1.0
   Compiling signal-hook v0.3.15
   Compiling chacha20poly1305 v0.9.1
   Compiling aes-gcm v0.9.2
   Compiling bincode v2.0.0-rc.3
   Compiling pin-project v1.1.0
   Compiling axum v0.6.18
   Compiling futures-executor v0.3.28
   Compiling headers-core v0.2.0
   Compiling sha1 v0.10.5
   Compiling futures v0.3.28
   Compiling kadmium v0.6.0
   Compiling headers v0.3.8
   Compiling tower v0.4.13
   Compiling serde_path_to_error v0.1.11
   Compiling http-range-header v0.3.0
   Compiling matchit v0.7.0
   Compiling sync_wrapper v0.1.2
   Compiling tower-http v0.4.0
   Compiling signal-hook-mio v0.2.3
   Compiling simple_asn1 v0.6.2
   Compiling snarkos-node-tcp v2.0.2 (/root/leo/snarkOS/node/tcp)
   Compiling pem v1.1.1
   Compiling tokio-stream v0.1.14
   Compiling instant v0.1.12
   Compiling linked-hash-map v0.5.6
   Compiling backoff v0.4.0
   Compiling jsonwebtoken v8.3.0
   Compiling memoffset v0.7.1
   Compiling regex-syntax v0.6.29
   Compiling crossterm v0.25.0
   Compiling tikv-jemalloc-sys v0.5.3+5.3.0-patched
   Compiling regex-automata v0.1.10
   Compiling overload v0.1.1
   Compiling cassowary v0.3.0
   Compiling axum-extra v0.7.4
   Compiling unicode-segmentation v1.10.1
   Compiling same-file v1.0.6
   Compiling tui v0.19.0
   Compiling walkdir v2.3.3
   Compiling matchers v0.1.0
   Compiling nu-ansi-term v0.46.0
   Compiling crossterm v0.26.1
   Compiling tracing-log v0.1.3
   Compiling sharded-slab v0.1.4
   Compiling thread_local v1.1.7
   Compiling static_assertions v1.1.0
   Compiling tracing-subscriber v0.3.17
   Compiling nix v0.26.2
   Compiling snarkos v2.0.2 (/root/leo/snarkOS)
error: failed to run custom build command for `snarkos v2.0.2 (/root/leo/snarkOS)`

Caused by:
  process didn't exit successfully: `/root/leo/snarkOS/target/release/build/snarkos-e900855db5584cfc/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'The license in "./display/src/pages/overview.rs" is either missing or it doesn't match the expected string!', build.rs:46:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `snarkos v2.0.2 (/root/leo/snarkOS)`, intermediate artifacts can be found at `/root/leo/snarkOS/target`

```

**Comment by liolikus** [comment]
Some screens from Discord.
![image](https://github.com/AleoHQ/snarkOS/assets/85246338/230976f4-7745-493e-b4a4-b2bbd7211a31)
![image](https://github.com/AleoHQ/snarkOS/assets/85246338/50f7e8c8-01eb-41c9-b084-b17dd657e1ee)
![image](https://github.com/AleoHQ/snarkOS/assets/85246338/a055d7b2-bed3-46f6-810d-43292b43257b)

**Comment by liolikus** [comment]
https://github.com/AleoHQ/snarkOS/pull/2401 ?

**Comment by liolikus** [comment]
Fidex with https://github.com/AleoHQ/snarkOS/pull/2404
