### ISSUE TITLE
Failure on block 14931: `Failed to finalize transactions: Mismatch in finalize operations for an accepted execute`

### ISSUE THREAD

**Issue by rpyell-aleo** [AleoHQ/snarkOS#2462]
## 🐛 Bug Report

On commit `b2eae5950` , validator fails to sync past block `14931` after a clean build and `snarkos clean` command. The error in sync/validation of synced data results in the validator "becoming ready" kibg before it actually reaches 100% sync.

I've also zipped up the ledger in the event it is useful for troubleshooting: https://drive.google.com/file/d/1CqBG4KsIPqTAUFuIrynI60Hazk6tYQEZ/view?usp=sharing

Logs at failure point:
```
Jun 20 20:57:19 validator32 snarkos[839168]: 2023-06-20T20:57:19.301853Z DEBUG snarkos_node_cdn::blocks: Requesting blocks 21250 to 21300 (of 278100)
Jun 20 20:57:19 validator32 snarkos[839168]: thread 'tokio-runtime-worker' panicked at 'Integer addition failed on: 200u8 and 100u8', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkvm-console-network-environment-0.11.7/src/environment.rs:60:9
Jun 20 20:57:19 validator32 snarkos[839168]: stack backtrace:
Jun 20 20:57:19 validator32 snarkos[839168]:    0: rust_begin_unwind
Jun 20 20:57:19 validator32 snarkos[839168]:              at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
Jun 20 20:57:19 validator32 snarkos[839168]:    1: core::panicking::panic_fmt
Jun 20 20:57:19 validator32 snarkos[839168]:              at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
Jun 20 20:57:19 validator32 snarkos[839168]:    2: core::panicking::panic_display
Jun 20 20:57:19 validator32 snarkos[839168]:    3: snarkvm_console_network_environment::environment::Environment::halt
Jun 20 20:57:19 validator32 snarkos[839168]:    4: snarkvm_synthesizer::process::finalize::<impl snarkvm_synthesizer::process::Process<N>>::finalize_execution::{{closure}}::{{closure}}
Jun 20 20:57:19 validator32 snarkos[839168]:    5: snarkvm_synthesizer::process::finalize::<impl snarkvm_synthesizer::process::Process<N>>::finalize_execution
Jun 20 20:57:19 validator32 snarkos[839168]:    6: snarkvm_ledger::Ledger<N,C>::add_next_block
Jun 20 20:57:19 validator32 snarkos[839168]:    7: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
Jun 20 20:57:19 validator32 snarkos[839168]:    8: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
Jun 20 20:57:19 validator32 snarkos[839168]:    9: tokio::runtime::task::core::Core<T,S>::poll
Jun 20 20:57:19 validator32 snarkos[839168]:   10: tokio::runtime::task::harness::Harness<T,S>::poll
Jun 20 20:57:19 validator32 snarkos[839168]:   11: tokio::runtime::blocking::pool::Inner::run
Jun 20 20:57:19 validator32 snarkos[839168]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Jun 20 20:57:20 validator32 snarkos[839168]: 2023-06-20T20:57:20.574985Z  WARN snarkos_node_cdn::blocks: Failed to process block 14931: Failed to finalize transactions: Mismatch in finalize operations for an accepted execute
Jun 20 20:57:20 validator32 snarkos[839168]: 2023-06-20T20:57:20.575029Z DEBUG snarkos_node_cdn::blocks: Synced the ledger up to block 14930
Jun 20 20:57:22 validator32 snarkos[839168]: 2023-06-20T20:57:22.482167Z DEBUG tcp{name="0"}: snarkos_node_tcp::tcp: The node is ready
```

## Steps to Reproduce

```
git clone https://github.com/AleoHQ/snarkOS.git
cd snarkOS
git checkout b2eae5950
./build_ubuntu.sh
snarkos start --nodisplay --rest "0.0.0.0:12345" --logfile /dev/null --verbosity 4 --validator APrivateKey******
```

## Expected Behavior

Validator should sync all the way to tip and then start, not start at the 4% point.

## Your Environment

- b2eae5950
- rustc 1.69.0
- Ubuntu 22.04.2 LTS

**Comment by howardwu** [comment]
Is this issue still reproducible on a clean node from genesis?

**Comment by rpyell-aleo** [comment]
Using the current deployment this is no longer reproducible so I'll go ahead and close this.
