### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by kellpossible** [AleoHQ/snarkOS#441]
## 🐛 Bug Report

I have some code to test decrypting a transaction record. In this example I decided to modify the encrypted record slightly so that it would not successfully decrypt.

```rust
use snarkos_objects::AccountViewKey;
use snarkos_rpc_client::{SnarkOSRpcConn, methods::get_block_count};
use snarkos_dpc::{record_encryption::RecordEncryption, SystemParameters, instantiated::Components, EncryptedRecord};
use snarkos_utilities::bytes::FromBytes;

use std::str::FromStr;

pub fn decrypt_transaction_record() {
    let system_parameters = SystemParameters::load().unwrap();
    let account_view_key = AccountViewKey::<Components>::from_str("AViewKey1m8gvywHKHKfUzZiLiLoHedcdHEjKwo5TWo6efz8gK7wF").unwrap();

    let encrypted_transaction_bytes = hex::decode(
              "081e4a0d39c6e22d8b4a170af02311f4ba76b4ffba99811\
                    0c6ae9854d288bb1b0df491df24446102ccee297d29ad376af\
                    b46718ce9c9535bfa4596f831e8979807aa9a81ee5f25dbf9d\
                    6046ce7012e976f6031419d535ffec255fc3e5e919ee00a8b2\
                    7b4eaa21b83bffdc9cf417dd760352170915a292761ae4b33f\
                    8604dd82601b345fdf4142ffc422387b06e05836ddae59e5bc\
                    b8782e458e79de894be85980b2a984492dc4e5e3928b73e9c3\
                    31ed6fe901f23204ce246c441d00be2f0b2b00573cf8e16d65\
                    664416da025ce9d10179ae6c60a8ac3c94aef6d06adeab8c09\
                    904eaeb83825f15894b84f394ed70e7b9ddb6dfacbeaa30bed\
                    7063dcb9796766e125c00").unwrap();

    let encrypted_record = EncryptedRecord::read(&encrypted_transaction_bytes[..]).unwrap();

    let record = RecordEncryption::decrypt_record(&system_parameters, &account_view_key, &encrypted_record).unwrap();
    println!("record: {:?}", record);
}
```

I get the following panic:

```txt
thread 'snarkos::tests::test_decrypt_record' panicked at 'assertion failed: `(left == right)`
  left: `QuadraticNonResidue`,
 right: `QuadraticResidue`', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-algorithms-1.1.4/src/encoding/elligator2.rs:232:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84b047bf64dfcfa12867781e9c23dfa4f2e6082c/library/std/src/panicking.rs:475
   1: std::panicking::begin_panic_fmt
             at /rustc/84b047bf64dfcfa12867781e9c23dfa4f2e6082c/library/std/src/panicking.rs:429
   2: snarkos_algorithms::encoding::elligator2::Elligator2<P,G>::decode
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-algorithms-1.1.4/src/encoding/elligator2.rs:232
   3: snarkos_dpc::base_dpc::record::record_serializer::decode_from_group
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-dpc-1.1.4/src/base_dpc/record/record_serializer.rs:50
   4: <snarkos_dpc::base_dpc::record::record_serializer::RecordSerializer<C,P,G> as snarkos_models::dpc::record_serializer::RecordSerializerScheme>::deserialize
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-dpc-1.1.4/src/base_dpc/record/record_serializer.rs:287
   5: snarkos_dpc::base_dpc::record::record_encryption::RecordEncryption<C>::decrypt_record
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-dpc-1.1.4/src/base_dpc/record/record_encryption.rs:156
   6: voyager::snarkos::decrypt_transaction_record
```

## Expected Behavior

I wouldn't expect the code to panic like this, I think it should return an error that can be handled.

## Your Environment

snarkOS libraries `1.1.4`
Rust `1.47.0-beta.2`
Linux

**Comment by kellpossible** [comment]
I'm also getting the same kind of panic while decrypting a record in the transaction `011c708e9025865e86ba38a7122883050aa8629438666ff74ca2b64fd9e6d0b8`:

```txt
  The application panicked (crashed).
Message:  assertion failed: `(left == right)`
  left: `QuadraticNonResidue`,
 right: `QuadraticResidue`
Location: ~/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-algorithms-1.1.4/src/encoding/elligator2.rs:232
  
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  
   0: voyager::snarkos::decryptrecord with context=block: 011c708e9025865e86ba38a7122883050aa8629438666ff74ca2b64fd9e6d0b8, transaction: 1a12baba9b2ba6be3b3d107c7780c9215d14506b7a9d220cc73cf936855f6a40
      at src/snarkos.rs:309
   1: voyager::snarkos::decryptrecord[s] with block=011c708e9025865e86ba38a7122883050aa8629438666ff74ca2b64fd9e6d0b8
      at src/snarkos.rs:291
   2: voyager::snarkos::naive_linear_scan with addresses=["http://us1.testnet1.aleo.network:3030"]
      at src/snarkos.rs:122

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 15 frames hidden ⋮                              
  16: snarkos_algorithms::encoding::elligator2::Elligator2<P,G>::decode::h63cc25e280c1ecb5
      at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-algorithms-1.1.4/src/encoding/elligator2.rs:232
  17: snarkos_dpc::base_dpc::record::record_serializer::decode_from_group::habf5c015c8c3a3b4
      at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-dpc-1.1.4/src/base_dpc/record/record_serializer.rs:50
  18: <snarkos_dpc::base_dpc::record::record_serializer::RecordSerializer<C,P,G> as snarkos_models::dpc::record_serializer::RecordSerializerScheme>::deserialize::hc8eb311730b06e4e
      at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-dpc-1.1.4/src/base_dpc/record/record_serializer.rs:273
  19: snarkos_dpc::base_dpc::record::record_encryption::RecordEncryption<C>::decrypt_record::h364e4bf1934a42d7
      at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-dpc-1.1.4/src/base_dpc/record/record_encryption.rs:156
  20: voyager::snarkos::naive_linear_scan::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}
```

**Comment by kellpossible** [comment]
This same bug has bitten me again in a different spot now

**Comment by kellpossible** [comment]
I've also had this cause failure in tests even with the `catch_unwind` workaround due to panic handler triggering something, so I've also had to temporarily disable panic handler before calling `decrypt_record()`.
